version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      security:
        patterns:
          - "*"
        update-types:
          - "security"
      all-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]

